name: coverage badge
on:
 push:
   branches: [ master ]

jobs:
 checks:
   runs-on: ubuntu-20.04
   steps:
   - uses: actions/checkout@v2

   - name: Use Node.js
     uses: actions/setup-node@v2
     with:
       node-version: '14'

   - name: Install dependencies
     run: npm ci

   - name: Run unit tests with coverage
     run: |
       SUMMARY="$(npm test -- --coverage --coverageReporters=text-summary | tail -3 | head -1)"
       TOKENS=($SUMMARY)
       echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV

   - name: Create Coverage Badge
     uses: schneegans/dynamic-badges-action@v1.1.0
     with:
       auth: ${{ secrets.GIST_SECRET }}
       gistID: 21872732f8434b07c34fa3a1a95c530a
       filename: japanese_songs_coverage.json
       label: coverage
       message: ${{ env.COVERAGE }}
       namedLogo: jest
       color: blue
       logoColor: lightblue
